<div class="right">
    <div class="darkgreen_button left">
            <a href="<?php echo $this->baseUrl('account/edit-profile'); ?>">EDIT PROFILE<span>Edit your profile</span></a>
    </div><!-- END purple_button   -->
    <div class="orange_button left">
            <a href="<?php echo $this->baseUrl('account/outbox'); ?>">OUTBOX<span>View sent messages</span></a>
    </div><!-- END blue_button   -->
    <div class="purple_button left">
            <a href="<?php echo $this->baseUrl('account/inbox'); ?>">INBOX<span>Check incoming messages</span>
            </a>
    </div><!-- END gray_button   -->
    <div class="clear"></div>    
</div>
<div class="clear"></div>