<div id="container" class="projects">
    <div class="main_box left members_list project_list member_project" style="width:920px;">
        <?php echo $this->partial('project/_archive-projects-tab.phtml', 
                                  array('tabActive1' => 'active', 'tabActive2' => ''));?>    
        
        <div class="clear"></div>
        <div class="pagination left"  style="margin-top:20px;">
            <?php echo $this->pagination?>
        </div><!-- END pagination   -->
        
        <?php echo $this->partial('project/_sorting-links.phtml', 
                                  array('action' => 'archive-bidded-projects', 'searchType' => $this->searchType));?>
        
        <?php
        if(!empty($this->archiveBiddedProjects)) {
            foreach ($this->archiveBiddedProjects as $archiveBiddedProject) {
        ?>
        
        <div class="project_box left">
            <a href="<?php echo $this->baseUrl('project/project-details'); ?>/<?php echo $archiveBiddedProject->getProjectId()?>" 
               class="blue_title">

            <?php
            if(strlen($archiveBiddedProject->getProjectTitle()) < 18) {
                echo $archiveBiddedProject->getProjectTitle();
            } else {
                echo substr($archiveBiddedProject->getproject_title(),0,18)."...";
            }
            ?>

            </a>
            <span class="gray_text">Status : Bid (<?php echo $archiveBiddedProject->getTotalBid()?> bids)</span>
            <span class="gray_text">Assigned to : 

            <? 
            if(!empty($this->assignedProjectsUsers[$archiveBiddedProject->getProjectId()])) {
                echo  $this->assignedProjectsUsers[$archiveBiddedProject->getProjectId()]['username'] . ' ';
            } else {
                echo "N.A";
            }
            ?>  

            </span>
            <span class="gray_text">Bid ending : 
                <?php echo date('d M Y',strtotime($archiveBiddedProject->getBidEndingDate())); ?>
            </span>
            <div class="blue_button">
                <a href="<?php echo $this->baseUrl('project/project-details'); ?>/<?php echo $archiveBiddedProject->getProjectId()?>">
                    BUDGET : &lt; $<?php echo round($archiveBiddedProject->getCost());?>
                </a>
            </div><!-- END blue_button   -->
            <span> 
                
            <?php
            if(!$archiveBiddedProject->getBidderFeedbackGiven() && $archiveBiddedProject->getCustom() == 1) { 
            ?>
                
                <a href="<?php echo $this->baseUrl('project/bidder_rating_page') 
                                    . '/' . $archiveBiddedProject->getProjectId() 
                                    . '/' . $archiveBiddedProject->getUserId()?>" 
                   style="color:blue;font-size:10px;" >
                    give feedback for this project
                </a> 
                
            <?
            }
            ?> 
            
            </span>
        </div><!-- END project_box (1)   -->

        <?
            }
        } else echo "<center><h3>You have no bidded project.</h3></center>";    
        ?>     

        <div class="clear"></div>

        <div class="pagination">
            <?php echo $this->pagination;?> 
        </div><!-- END mail_pagination   -->
    <!-- END project_list   -->   
    </div><!-- END new_in_cat   -->

    <?php echo $this->render('bottom-three-btn.phtml');?>

    <div class="clear"></div>
</div><!-- END container   -->