<div id="container" class="projects">
    <div class="main_box left members_list project_list member_project" style="width:920px;">
        <?php echo $this->partial('project/_projects-tab.phtml', 
                                  array('tabActive1' => '', 'tabActive2' => 'active'));?>
        
        <div class="pagination left" style="margin-top:20px;">
         <?php echo $this->pagination?>
        </div><!-- END pagination   -->
        
        <?php echo $this->partial('project/_sorting-links.phtml', 
                                  array('action' => 'bidded-projects', 'searchType' => $this->searchType));?>
        
        <?php
        if(!empty($this->biddedProjects)) {
            foreach ($this->biddedProjects as $biddedProject) {
        ?>
        
        <div class="project_box left">
            <a href="<?php echo $this->baseUrl('project/project-details'); ?>/<?php echo $biddedProject->getProjectId()?>" 
               class="blue_title">

            <?php
            if(strlen($biddedProject->getProjectTitle()) < 18) {
                echo $biddedProject->getProjectTitle();
            } else {
                echo substr($biddedProject->getproject_title(),0,18)."...";
            }
            ?>

            </a>
            <span class="gray_text">Status : Bid (<?php echo $biddedProject->getTotalBid()?> bids)</span>
            <span class="gray_text">Assigned to : 

            <? 
            if(!empty($this->assignedProjectsUsers[$biddedProject->getProjectId()])) {
                echo  $this->assignedProjectsUsers[$biddedProject->getProjectId()]['username'] . ' ';
            } else {
                echo "N.A";
            }
            ?>  

            </span>
            <span class="gray_text">Bid ending : 
                <?php echo date('d M Y',strtotime($biddedProject->getBidEndingDate())); ?>
            </span>
            <div class="purple_button">
                <a href="<?php echo $this->baseUrl('project/project-details'); ?>/<?php echo $biddedProject->getProjectId()?>">
                    BUDGET : &lt; $<?php echo round($biddedProject->getCost());?>
                </a>
            </div><!-- END blue_button   -->
            <span> 
                
            <?php
            if(!$biddedProject->getBidderFeedbackGiven() && $biddedProject->getCustom() == 1) { 
            ?>
                
                <a href="<?php echo $this->baseUrl('project/bidder-rating') . '/' . $biddedProject->getProjectId() . '/' . $biddedProject->getUserId()?>" 
                   style="color:blue;font-size:10px;" >
                    give feedback for this project
                </a> 
                
            <?
            }
            ?> 
            
            </span>
        </div><!-- END project_box (1)   -->

        <?
            }
        } else echo "<center><h3>You have no bidded project.</h3></center>";    
        ?>     

        <div class="clear"></div>

        <div class="pagination">
            <?php echo $this->pagination;?> 
        </div><!-- END mail_pagination   -->
    <!-- END project_list   -->   
    </div><!-- END new_in_cat   -->

    <?php echo $this->render('bottom-three-btn.phtml');?>

    <div class="clear"></div>
</div><!-- END container   -->