<div class="left">
    <div class="<?php echo $this->class;?>" id="image">NO PHOTO</div>
    <center>
        <div style="margin-top: 10px; position: relative; z-index: 50;">
            <img id="loading" src="<?php echo $this->loadingImage;?>" style="display:none;">
        </div>
    </center> 
    <div id="file-uploader-demo1"></div>   
    <div class="clear"></div>
    <div id="upload">
        
        <?php 
        echo $this->{$this->element->helper}(
                 $this->element->getName(),
                 $this->element->getValue(),
                 $this->element->getAttribs()
             ) 
        ?>
        
    </div>
</div>