<div class="member_login" id="container">
	<div class="purple_button right">
		<a href="<?php echo $this->baseUrl('index/signup'); ?>">
            REGISTER TODAY<span>Registration is free, join now</span>
        </a>
	</div><!-- END purple_button   -->
	<div class="clear"></div>
    
	<div class="main_box">
		<h3>USER LOGIN</h3>
        <div style="color:red;margin-bottom:5px;font-size: 12px;"><?php echo $this->error;?></div>

        <?php echo $this->form;?>
        
		<div class="banner_ad left">banner ad</div>
		<div class="clear"></div>
	</div><!-- END main_box   -->    
</div>