<footer>
    <div class="footer_leftbg"></div>
    <div class="footer_rightbg"></div>
    <div class="footer_links">
        <div class="left">
            <span class="verified_logo"><img src="<?php echo $this->baseUrl('images/verified_logo_1.jpg'); ?>" alt="" /></span>
            <span class="verified_logo"><img src="<?php echo $this->baseUrl('images/verified_logo_2.jpg'); ?>" alt="" /></span>
        </div>
        <div class="right">
            <h2>TYPE OF PROJECTS</h2>
            <?php
            echo $this->placeholder('categories');
            ?>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div><!-- END footer_links   -->
    <nav>
        <ul class="footer_menu">
            <li><a href="<?php echo $this->baseUrl('/'); ?>#">About 3lance</a></li>
            <li>/</li>
            <li><a href="<?php echo $this->baseUrl('/'); ?>#">Contact Us</a></li>
            <li>/</li>
            <li><a href="<?php echo $this->baseUrl('/'); ?>#">Pricing & Packages</a></li>
            <li>/</li>
            <li><a href="<?php echo $this->baseUrl('/'); ?>#">FAQ</a></li>
            <li>/</li>
            <li><a href="<?php echo $this->baseUrl('/'); ?>#">Terms of Use</a></li>
            <li>/</li>
            <li><a href="<?php echo $this->baseUrl('/'); ?>#">Privacy Policy</a></li>
        </ul>
        <div class="clear"></div>
    </nav>
</footer><!-- END footer   -->